### ISSUE TITLE
Extend mock-continuum-login to have all the mocks in 

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer-mocks#8]
- [x] Rename to a better name
- [x] Update all the dependencies
- [x] Extend with mock reviewer-submission endpoints/schema

**Comment by Cooryd** [comment]
see branch `8-mock-submission`  - 

To facilitate reviewer-client browser tests this service needs to expose a mock endpoint for:

- [x] journal token exchange
- [x] continuum-auth service
- [ ] reviewer-submission /graphql

**Comment by Cooryd** [comment]
Will need to merge https://github.com/libero/reviewer-client/tree/36_add_mock_login_service and https://github.com/libero/reviewer/tree/update-mock-image to update image dependencies / configuration for reviwer-client and reviewer.
